### ISSUE TITLE
Automated failure detection in tst/testall.g with Jenkins

### ISSUE THREAD

**Issue by alex-konovalov** [fingolfin/PackageMaker#21]
To be able to detect automatically falling tests and optionally send a notification to package authors, we use the convention to print one of the following strings that may be seen in the code below:

```
if testresult then
  Print("#I  No errors detected while testing package ", pkgname, "\n");
else
  Print("#I  Errors detected while testing package ", pkgname, "\n");
fi;
```

I suggest to add such code block to the end of `tst/testall.g` and change its logic slightly to determine `testresult`. This will ensure that new packages will comply with the testing infrastructure from the start.

**Comment by fingolfin** [comment]
This should be resolved now, thanks to PackageMaker using `TestDirectory`
